[font]
size = 10

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[window]
decorations = "none"
opacity = 0.85
